services:
  testingdb:
    image: postgres:17-alpine
    ports:
      - "127.0.0.1:5430:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE:-testing}", "-U", "${DB_USERNAME:-testing}" ]
      retries: 3
      timeout: 5s
    environment:
      PGPASSWORD: '${DB_PASSWORD:-testing}'
      POSTGRES_DB: '${DB_DATABASE:-testing}'
      POSTGRES_USER: '${DB_USERNAME:-testing}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-testing}'
    tmpfs:
      - /var/lib/postgresql
  phpunit:
    build:
      context: ./
      dockerfile: Dockerfile.phpunit
    user: "1000:1000"
    volumes:
      - type: bind
        source: ./../
        target: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - testingdb
networks:
  default:
    ipam:
      config:
        - subnet: 192.168.171.0/24
